### PR TITLE
Feature/update for u8

### PR DESCRIPTION
**Pull request by Greven145**
Love the tool and have forked yet-another-factory-planner. With update 8 coming out to Early Access soon I wanted to update the planner and needed to parse the new doc file. There are some updates to the file format that add a few extra character and include a prefix on the class names, so those are accounted for here. I know things are busy based on your readme in the other repo, so hopefully this helps you and others that might want to use the new data.

- Updates NPM vulnerabilities
- Accounts for a new prefix to class names in U8 (0.8.1.3)
- Strip extra double quotes from some of producedIn values
- Add priority power switch to the list of buildable
- Add new unlocks to schematic unlock parser

### CODE REVIEW

**Comment by AppElent** [comment]
I like! Is there any way I can make use of itt already? Waiting for it

**Comment by Greven145** [comment]
@AppElent You can always go back to the commit on my repo and clone that. I'm also hosting it at https://yafp.game.gottselig.ca, though that has some enhancements (and a few bugs that need to be worked out).

**Comment by AppElent** [comment]
@Greven145 would it be possible to run the output of the cli and send it to me? 
On the previous version i just ran npx parse-docs --input ./docs_v700.json --output ./output_v700 once and I am using this output

**Comment by lunafoxfire** [comment]
Hello and thank you for your efforts. I am very sorry I never accepted this, but I had some major life events that affected my ability to maintain my github projects.

Good news though!! I am releasing a major update that will bring this tool up-to-date with 1.0. Should be released later today, actually.

Therefore I am closing this as out-of-date.

**Comment by AppElent** [comment]
Hi, only dev branch seems to be updated and no new npm package. Will this be live soon?

**Comment by lunafoxfire** [comment]
Hi, I've been very busy with life and work, and the scope of the changes I want to make has grown larger than I expected. I have rewritten a lot of the code with the goal of re-examining which fields of the satisfactory classes are extracted in order to make the tool as complete as possible. It should be done and released quite soon, as I just need to make one final pass over the parsing functions to actually extract all the data I want to.

**Pull request closed without merging**
